spring:
  application:
    name: liparibank-spring-target
  datasource:
    url: jdbc:mysql://localhost:3306/liparibank?useSSL=false&serverTimezone=UTC
    username: lipariuser
    password: liparipassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{correlationId:-no-correlation-id}] %logger{36} - %msg%n"
  level:
    root: INFO
    com.lipari.bank: DEBUG
